<a href="https://colab.research.google.com/github/TetianaDS/Python-For-DS/blob/main/%22hw_3_3_%D0%A0%D0%BE%D0%B7%D1%88%D0%B8%D1%80%D0%B5%D0%BD%D1%96_%D0%BC%D0%B5%D1%82%D0%BE%D0%B4%D0%B8_%D0%BE%D0%B1%D1%80%D0%BE%D0%B1%D0%BA%D0%B8_%D0%B4%D0%B0%D0%BD%D0%B8%D1%85_%D1%83_Pandas_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Домашнє завдання до теми "Розширені методи обробки даних у Pandas"

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

В цьому домашньому завданні продовжуємо працювати з набором даних `supermarket_sales.csv`.

0. Імпортуйте бібліотеку pandas та зчитайте дані у змінну `df` типу `pandas.DataFrame`.

In [10]:
import pandas as pd
df = pd.read_csv('drive/MyDrive/DS_course/data/supermarket_sales.csv')

1. Відсортуйте дані за спаданням ціни товара ('Unit price') і виведіть 5 перших рядочків на екран.

In [16]:
df.sort_values(by='Unit price', ascending=False).head(5)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
983,148-41-7930,C,Naypyitaw,Normal,Male,Health and beauty,99.96,7,34.986,734.706,1/23/2019,10:33,Cash,699.72,4.761905,34.986,6.1
122,219-22-9386,B,Mandalay,Member,Male,Sports and travel,99.96,9,44.982,944.622,3/9/2019,17:26,Credit card,899.64,4.761905,44.982,4.2
930,641-62-7288,B,Mandalay,Normal,Male,Home and lifestyle,99.92,6,29.976,629.496,3/24/2019,13:33,Ewallet,599.52,4.761905,29.976,7.1
494,437-53-3084,B,Mandalay,Normal,Male,Fashion accessories,99.89,2,9.989,209.769,2/26/2019,11:48,Ewallet,199.78,4.761905,9.989,7.1
283,667-92-0055,A,Yangon,Member,Male,Health and beauty,99.83,6,29.949,628.929,3/4/2019,15:02,Ewallet,598.98,4.761905,29.949,8.5

2. Знайдіть інвойс (рядок в даних) в категорії товарів `Electronic accessories`, в якому був куплений товар з найбільшою кількістю і найбільшою ціною. Виведіть цей рядок даних на екран.

In [88]:
filter = df[df['Product line'] == 'Electronic accessories']

In [107]:
print("Найвища ціна товару у замовленні")
max_price = filter['Unit price'].max()
filter.query("`Unit price` == @max_price")

Найвища ціна товару у замовленні

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
209,817-69-8206,B,Mandalay,Normal,Female,Electronic accessories,99.73,9,44.8785,942.4485,3/2/2019,19:42,Credit card,897.57,4.761905,44.8785,6.5

In [114]:
print("Найбільша кількість товару у замовленні")
max_quantity = filter['Quantity'].max()
filter.query("`Quantity` == @max_quantity").sort_values(by='Unit price', ascending=False)

Найбільша кількість товару у замовленні

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
105,704-48-3927,A,Yangon,Member,Male,Electronic accessories,88.67,10,44.335,931.035,1/12/2019,14:50,Ewallet,886.7,4.761905,44.335,7.3
988,267-62-7380,C,Naypyitaw,Member,Male,Electronic accessories,82.34,10,41.170,864.570,3/29/2019,19:12,Ewallet,823.4,4.761905,41.170,4.3
109,861-77-0145,C,Naypyitaw,Member,Male,Electronic accessories,81.97,10,40.985,860.685,3/3/2019,14:30,Cash,819.7,4.761905,40.985,9.2
457,533-33-5337,B,Mandalay,Normal,Male,Electronic accessories,79.39,10,39.695,833.595,2/7/2019,20:24,Cash,793.9,4.761905,39.695,6.2
314,227-07-4446,C,Naypyitaw,Member,Female,Electronic accessories,78.13,10,39.065,820.365,2/10/2019,20:51,Cash,781.3,4.761905,39.065,4.4
829,416-17-9926,A,Yangon,Member,Female,Electronic accessories,74.22,10,37.110,779.310,1/1/2019,14:42,Credit card,742.2,4.761905,37.110,4.3
887,884-80-6021,A,Yangon,Member,Female,Electronic accessories,73.47,10,36.735,771.435,3/23/2019,13:14,Ewallet,734.7,4.761905,36.735,9.5
761,525-09-8450,B,Mandalay,Normal,Male,Electronic accessories,72.13,10,36.065,757.365,1/31/2019,15:12,Credit card,721.3,4.761905,36.065,4.2
828,538-22-0304,C,Naypyitaw,Normal,Male,Electronic accessories,64.95,10,32.475,681.975,3/24/2019,18:27,Cash,649.5,4.761905,32.475,5.2
737,137-63-5492,C,Naypyitaw,Normal,Male,Electronic accessories,58.76,10,29.380,616.980,1/29/2019,14:26,Ewallet,587.6,4.761905,29.380,9.0
838,660-29-7083,C,Naypyitaw,Normal,Male,Electronic accessories,55.87,10,27.935,586.635,1/15/2019,15:01,Cash,558.7,4.761905,27.935,5.8
853,866-70-2814,B,Mandalay,Normal,Female,Electronic accessories,52.79,10,26.395,554.295,2/25/2019,11:58,Ewallet,527.9,4.761905,26.395,10.0
458,325-90-8763,C,Naypyitaw,Member,Female,Electronic accessories,46.57,10,23.285,488.985,1/27/2019,13:58,Cash,465.7,4.761905,23.285,7.6
674,811-03-8790,A,Yangon,Normal,Female,Electronic accessories,45.48,10,22.740,477.540,3/1/2019,10:22,Credit card,454.8,4.761905,22.740,4.8
75,732-94-0499,C,Naypyitaw,Normal,Female,Electronic accessories,41.65,10,20.825,437.325,1/13/2019,17:04,Credit card,416.5,4.761905,20.825,5.4
290,139-20-0155,B,Mandalay,Member,Male,Electronic accessories,40.30,10,20.150,423.150,1/24/2019,17:37,Credit card,403.0,4.761905,20.150,7.0
811,380-60-5336,A,Yangon,Normal,Female,Electronic accessories,40.26,10,20.130,422.730,2/24/2019,18:06,Credit card,402.6,4.761905,20.130,5.0
481,246-11-3901,C,Naypyitaw,Normal,Female,Electronic accessories,32.80,10,16.400,344.400,2/15/2019,12:12,Cash,328.0,4.761905,16.400,6.2
649,740-11-5257,C,Naypyitaw,Normal,Male,Electronic accessories,24.74,10,12.370,259.770,2/24/2019,16:44,Cash,247.4,4.761905,12.370,7.1
532,857-67-9057,B,Mandalay,Normal,Male,Electronic accessories,22.95,10,11.475,240.975,2/6/2019,19:20,Ewallet,229.5,4.761905,11.475,8.2
872,544-55-9589,B,Mandalay,Member,Female,Electronic accessories,21.43,10,10.715,225.015,1/28/2019,11:51,Cash,214.3,4.761905,10.715,6.2
752,807-14-7833,A,Yangon,Member,Female,Electronic accessories,17.42,10,8.710,182.910,2/22/2019,12:30,Ewallet,174.2,4.761905,8.710,7.0

In [110]:
filter.query("`Unit price` == @max_price & Quantity == @max_quantity")

Empty DataFrame
Columns: [Invoice ID, Branch, City, Customer type, Gender, Product line, Unit price, Quantity, Tax 5%, Total, Date, Time, Payment, cogs, gross margin percentage, gross income, Rating]
Index: []

3.1. Створіть нову колонку в даних `Rating Category`, яка визначає категорію рейтингу (`Rating`): високий, середній чи низький за наступним правилом:
- якщо рейтинг вищий або рівний 8 - то він високий (`High`)
- якщо рейтинг від 6 до 8 не включаючи - то він середній (`Medium`)
- інакше - низький (`Low`).

In [133]:
def rating(a):
    if a >=8:
        return 'High'
    elif a >=6 and a <8:
        return 'Medium'
    else:
        return 'Low'
df['Rating Category'] = df.Rating.apply(rating).astype('category')

3.2. Виведіть, який відсоток даних становить кожне зі значень категорій рейтингу.

In [135]:
df['Rating Category'].value_counts(normalize=True)*100

Rating Category
Medium    35.6
High      32.9
Low       31.5
Name: proportion, dtype: float64

4.1. Запустіть код нижче аби створити змінну `time`. Ця змінна містить час в форматі "година:хвилина". Напишіть функцію `get_hour`, яка буде зі змінної формату як `time` дістати лише години і конвертувати їх у тип `int`.

Запустіть написану функцію на змінній `time` та перевірте правильність роботи функції.

In [136]:
time = '11:28'

In [161]:
def get_hour(x:str):
    value = x.split(':')[0]
    return int(value)

In [162]:
get_hour(time)

11

4.2. З допомогою функції `get_hour` і метода `DataFrame.apply()` створіть нову колонку `Hour` в нашому наборі даних, яка буде містити години здійснення покупки, обчислені на основі часу здійснення покупки `Time`.

In [190]:
df['Hour'] = df.Time.apply(get_hour)

4.3. Виведіть кількість значень за кожною годиною покупки і дайте відповідь "О яких годинах найбільше здійснюють покупок покупці і чому на Ваш погляд саме о цих годинах? Чи це слогічно, що найбільше покупок саме в ці години?".

In [197]:
df['Hour'].value_counts().sort_values(ascending=False)

Hour
19    113
13    103
15    102
10    101
18     93
11     90
12     89
14     83
16     77
20     75
17     74
Name: count, dtype: int64

Піковими годинами є 19, 13, 15 та 10 години:
 - 13 та 15 - можна пояснити, що це час обідньої перерви й тому, більше покупців;
 - 10 та 19 - час, коли покупці добираються на та з роботи відповідно.
 Тому можна висунути гіпотезу, що цей магазин розташований неподалік зупинки транспорту

5. Виведіть середнє значення чеку (`Total`) для покупок в містах, наявних в даних, за допомогою функції `groupby`.

In [213]:
df.groupby('City')['Total'].mean()

City
Mandalay     319.872506
Naypyitaw    337.099715
Yangon       312.354031
Name: Total, dtype: float64

6. Виведіть кількість покупок, середнє, мінімальне та максимальне значення для загальної суми чеку (Total) в містах, наявних в даних, за допомогою функції groupby.
Зробіть висновки з цих показників та дайте рекомендації для мережі супермаркетів.

In [217]:
df.groupby('City')['Total'].agg(['count', 'mean', 'min', 'max', 'sum'])

           count        mean      min      max          sum
City
Mandalay     332  319.872506  18.6375  1022.49  106197.6720
Naypyitaw    328  337.099715  10.6785  1042.65  110568.7065
Yangon       340  312.354031  12.6945  1039.29  106200.3705

Місто Naypyitaw має найвищий показник по середньому чеку й по загальній сумі виторгу. В той час як кількість чеків найменша.
Міста Yangon та Mandalay на одному рівні по показнику загального виторгу. Та в Yangon - найбільша кількість замовлень.
Рекомендації:
-  Yangon - працювати над збільшенням середнього чеку(консультації продавців, допродаж на касі);
-  Naypyitaw - потрібно збільшувати кількість замовлень(працювати з рекламою, проводити промо для залучення нових клієнтів та переведення їх в статус постійних)
-  Mandalay - середні значення показників, лише мінімальний чек є найвищим по всіх містам, хоча середній чек на посередньому рівні. Тобто, потрібно працювати над збільшенням середнього чеку, аналогічно Yangon

7. Ми внесли деякі зміни в наш набір даних, тож, давайте запишемо результат у файл. Запишіть оновлену версію даних у файл `supermarket_sales_enriched.csv`. Зверніть увагу, аби не записати нічого зайвого, наприклад, індекси рядків нам в файлі не потрібні, оскільки вони стандартні.

In [219]:
df.to_csv('drive/MyDrive/DS_course/data/supermarket_sales_enriched.csv', index=False)

In [223]:
pd.read_csv('drive/MyDrive/DS_course/data/supermarket_sales_enriched.csv', nrows = 3)

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating,Rating Category,Hour
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,1/5/2019,13:08,Ewallet,522.83,4.761905,26.1415,9.1,High,13
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,3/8/2019,10:29,Cash,76.40,4.761905,3.8200,9.6,High,10
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,3/3/2019,13:23,Credit card,324.31,4.761905,16.2155,7.4,Medium,13